#### 시퀀스 자료형

In [1]:
a = [10, 20, 30, 40, 50]

In [2]:
len(a)

5

In [3]:
c = 'Hello, python'

In [4]:
c*2

'Hello, pythonHello, python'

In [5]:
c[0]

'H'

#### 인덱스를 알게 되었으니
- 인덱스를 가지고 슬라이싱
- range(시작인덱스:끝인덱스:증가폭)

In [6]:
a[1:3]

[20, 30]

In [7]:
a[1]

20

In [8]:
a[2]

30

In [9]:
a[0:5:2]

[10, 30, 50]

In [10]:
a

[10, 20, 30, 40, 50]

In [11]:
a[0:]

[10, 20, 30, 40, 50]

In [12]:
a[0::]

[10, 20, 30, 40, 50]

In [13]:
a[::]

[10, 20, 30, 40, 50]

#### 반복문으로 시퀀스 객체를 접근해 보자

In [15]:
for i in range(len(a)):
  print(a[i], end=' ')

10 20 30 40 50

In [16]:
for i in a:
  print(i, end=' ')

10 20 30 40 50

In [17]:
for i in range(len(a)):
  print(a[i] * 20)

200
400
600
800
1000

In [18]:
# 새로운 리스트를 만들어서 값을 넣으려면
# append

c = []
for i in range(len(a)):
  c.append(a[i] * 10)

In [19]:
print(a)
print(c)

[10, 20, 30, 40, 50]
[100, 200, 300, 400, 500]

In [20]:
import pandas as pd

df = pd.read_csv('mpg.csv')

In [30]:
df.rename(columns={'class' : 'category'}, inplace=True)

In [31]:
# 데이터프레임의 컬럼 출력하기
for i in df:
  print(i)

manufacturer
model
displ
year
cyl
trans
drv
cty
hwy
fl
category
mean

- 리스트는 접근하는 방식이
- 반복문에서 리스트 를 넣어서

In [32]:
# zip 함수를 이용하기

mean = []
for i, j in zip(df.cty, df.hwy):
  # print(i, j)
  mean.append((i+j)/2)

In [33]:
df['mean'] = mean

In [34]:
df

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category,mean
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,23.5
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,25.0
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,25.5
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,25.5
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize,23.5
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize,25.0
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize,21.0
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize,22.0
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize,21.5

In [35]:
for i in df.model:
  #print(i)
  if i == 'malibu':
    print(i)

malibu
malibu
malibu
malibu
malibu

In [36]:
for i, j in enumerate(df.model):
  if j == 'malibu':
    print(i, j)

32 malibu
33 malibu
34 malibu
35 malibu
36 malibu

In [37]:
df

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category,mean
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,23.5
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,25.0
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,25.5
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,25.5
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize,23.5
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize,25.0
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize,21.0
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize,22.0
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize,21.5

In [38]:
df.model

0          a4
1          a4
2          a4
3          a4
4          a4
        ...
229    passat
230    passat
231    passat
232    passat
233    passat
Name: model, Length: 234, dtype: object

In [39]:
for idx, row in df.iterrows():
  print(idx, row)

0 manufacturer        audi
model                 a4
displ                1.8
year                1999
cyl                    4
trans           auto(l5)
drv                    f
cty                   18
hwy                   29
fl                     p
category         compact
mean                23.5
Name: 0, dtype: object
1 manufacturer          audi
model                   a4
displ                  1.8
year                  1999
cyl                      4
trans           manual(m5)
drv                      f
cty                     21
hwy                     29
fl                       p
category           compact
mean                  25.0
Name: 1, dtype: object
2 manufacturer          audi
model                   a4
displ                  2.0
year                  2008
cyl                      4
trans           manual(m6)
drv                      f
cty                     20
hwy                     31
fl                       p
category           compact
mean                  25.5
Name: 2, dtype: object
3 manufacturer        audi
model                 a4
displ                2.0
year                2008
cyl                    4
trans           auto(av)
drv                    f
cty                   21
hwy                   30
fl                     p
category         compact
mean                25.5
Name: 3, dtype: object
4 manufacturer        audi
model                 a4
displ                2.8
year                1999
cyl                    6
trans           auto(l5)
drv                    f
cty                   16
hwy                   26
fl                     p
category         compact
mean                21.0
Name: 4, dtype: object
5 manufacturer          audi
model                   a4
displ                  2.8
year                  1999
cyl                      6
trans           manual(m5)
drv                      f
cty                     18
hwy                     26
fl                       p
category           compact
mean                  22.0
Name: 5, dtype: object
6 manufacturer        audi
model                 a4
displ                3.1
year                2008
cyl                    6
trans           auto(av)
drv                    f
cty                   18
hwy                   27
fl                     p
category         compact
mean                22.5
Name: 6, dtype: object
7 manufacturer          audi
model           a4 quattro
displ                  1.8
year                  1999
cyl                      4
trans           manual(m5)
drv                      4
cty                     18
hwy                     26
fl                       p
category           compact
mean                  22.0
Name: 7, dtype: object
8 manufacturer          audi
model           a4 quattro
displ                  1.8
year                  1999
cyl                      4
trans             auto(l5)
drv                      4
cty                     16
hwy                     25
fl                       p
category           compact
mean                  20.5
Name: 8, dtype: object
9 manufacturer          audi
model           a4 quattro
displ                  2.0
year                  2008
cyl                      4
trans           manual(m6)
drv                      4
cty                     20
hwy                     28
fl                       p
category           compact
mean                  24.0
Name: 9, dtype: object
10 manufacturer          audi
model           a4 quattro
displ                  2.0
year                  2008
cyl                      4
trans             auto(s6)
drv                      4
cty                     19
hwy                     27
fl                       p
category           compact
mean                  23.0
Name: 10, dtype: object
11 manufacturer          audi
model           a4 quattro
displ                  2.8
year                  1999
cyl                      6
trans             auto(l5)
drv                      4
cty                     15
hwy                     25
fl                       p
category           compact
mean                  20.0
Name: 11, dtype: object
12 manufacturer          audi
model           a4 quattro
displ                  2.8
year                  1999
cyl                      6
trans           manual(m5)
drv                      4
cty                     17
hwy                     25
fl                       p
category           compact
mean                  21.0
Name: 12, dtype: object
13 manufacturer          audi
model           a4 quattro
displ                  3.1
year                  2008
cyl                      6
trans             auto(s6)
drv                      4
cty                     17
hwy                     25
fl                       p
category           compact
mean                  21.0
Name: 13, dtype: object
14 manufacturer          audi
model           a4 quattro
displ                  3.1
year                  2008
cyl                      6
trans           manual(m6)
drv                      4
cty                     15
hwy                     25
fl                       p
category           compact
mean                  20.0
Name: 14, dtype: object
15 manufacturer          audi
model           a6 quattro
displ                  2.8
year                  1999
cyl                      6
trans             auto(l5)
drv                      4
cty                     15
hwy                     24
fl                       p
category           midsize
mean                  19.5
Name: 15, dtype: object
16 manufacturer          audi
model           a6 quattro
displ                  3.1
year                  2008
cyl                      6
trans             auto(s6)
drv                      4
cty                     17
hwy                     25
fl                       p
category           midsize
mean                  21.0
Name: 16, dtype: object
17 manufacturer          audi
model           a6 quattro
displ                  4.2
year                  2008
cyl                      8
trans             auto(s6)
drv                      4
cty                     16
hwy                     23
fl                       p
category           midsize
mean                  19.5
Name: 17, dtype: object
18 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             14
hwy                             20
fl                               r
category                       suv
mean                          17.0
Name: 18, dtype: object
19 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             11
hwy                             15
fl                               e
category                       suv
mean                          13.0
Name: 19, dtype: object
20 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             14
hwy                             20
fl                               r
category                       suv
mean                          17.0
Name: 20, dtype: object
21 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.7
year                          1999
cyl                              8
trans                     auto(l4)
drv                              r
cty                             13
hwy                             17
fl                               r
category                       suv
mean                          15.0
Name: 21, dtype: object
22 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          6.0
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             12
hwy                             17
fl                               r
category                       suv
mean                          14.5
Name: 22, dtype: object
23 manufacturer     chevrolet
model             corvette
displ                  5.7
year                  1999
cyl                      8
trans           manual(m6)
drv                      r
cty                     16
hwy                     26
fl                       p
category           2seater
mean                  21.0
Name: 23, dtype: object
24 manufacturer    chevrolet
model            corvette
displ                 5.7
year                 1999
cyl                     8
trans            auto(l4)
drv                     r
cty                    15
hwy                    23
fl                      p
category          2seater
mean                 19.0
Name: 24, dtype: object
25 manufacturer     chevrolet
model             corvette
displ                  6.2
year                  2008
cyl                      8
trans           manual(m6)
drv                      r
cty                     16
hwy                     26
fl                       p
category           2seater
mean                  21.0
Name: 25, dtype: object
26 manufacturer    chevrolet
model            corvette
displ                 6.2
year                 2008
cyl                     8
trans            auto(s6)
drv                     r
cty                    15
hwy                    25
fl                      p
category          2seater
mean                 20.0
Name: 26, dtype: object
27 manufacturer     chevrolet
model             corvette
displ                  7.0
year                  2008
cyl                      8
trans           manual(m6)
drv                      r
cty                     15
hwy                     24
fl                       p
category           2seater
mean                  19.5
Name: 27, dtype: object
28 manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.3
year                       2008
cyl                           8
trans                  auto(l4)
drv                           4
cty                          14
hwy                          19
fl                            r
category                    suv
mean                       16.5
Name: 28, dtype: object
29 manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.3
year                       2008
cyl                           8
trans                  auto(l4)
drv                           4
cty                          11
hwy                          14
fl                            e
category                    suv
mean                       12.5
Name: 29, dtype: object
30 manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.7
year                       1999
cyl                           8
trans                  auto(l4)
drv                           4
cty                          11
hwy                          15
fl                            r
category                    suv
mean                       13.0
Name: 30, dtype: object
31 manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       6.5
year                       1999
cyl                           8
trans                  auto(l4)
drv                           4
cty                          14
hwy                          17
fl                            d
category                    suv
mean                       15.5
Name: 31, dtype: object
32 manufacturer    chevrolet
model              malibu
displ                 2.4
year                 1999
cyl                     4
trans            auto(l4)
drv                     f
cty                    19
hwy                    27
fl                      r
category          midsize
mean                 23.0
Name: 32, dtype: object
33 manufacturer    chevrolet
model              malibu
displ                 2.4
year                 2008
cyl                     4
trans            auto(l4)
drv                     f
cty                    22
hwy                    30
fl                      r
category          midsize
mean                 26.0
Name: 33, dtype: object
34 manufacturer    chevrolet
model              malibu
displ                 3.1
year                 1999
cyl                     6
trans            auto(l4)
drv                     f
cty                    18
hwy                    26
fl                      r
category          midsize
mean                 22.0
Name: 34, dtype: object
35 manufacturer    chevrolet
model              malibu
displ                 3.5
year                 2008
cyl                     6
trans            auto(l4)
drv                     f
cty                    18
hwy                    29
fl                      r
category          midsize
mean                 23.5
Name: 35, dtype: object
36 manufacturer    chevrolet
model              malibu
displ                 3.6
year                 2008
cyl                     6
trans            auto(s6)
drv                     f
cty                    17
hwy                    26
fl                      r
category          midsize
mean                 21.5
Name: 36, dtype: object
37 manufacturer          dodge
model           caravan 2wd
displ                   2.4
year                   1999
cyl                       4
trans              auto(l3)
drv                       f
cty                      18
hwy                      24
fl                        r
category            minivan
mean                   21.0
Name: 37, dtype: object
38 manufacturer          dodge
model           caravan 2wd
displ                   3.0
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
mean                   20.5
Name: 38, dtype: object
39 manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      16
hwy                      22
fl                        r
category            minivan
mean                   19.0
Name: 39, dtype: object
40 manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      16
hwy                      22
fl                        r
category            minivan
mean                   19.0
Name: 40, dtype: object
41 manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
mean                   20.5
Name: 41, dtype: object
42 manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
mean                   20.5
Name: 42, dtype: object
43 manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      11
hwy                      17
fl                        e
category            minivan
mean                   14.0
Name: 43, dtype: object
44 manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      15
hwy                      22
fl                        r
category            minivan
mean                   18.5
Name: 44, dtype: object
45 manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      15
hwy                      21
fl                        r
category            minivan
mean                   18.0
Name: 45, dtype: object
46 manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   2008
cyl                       6
trans              auto(l6)
drv                       f
cty                      16
hwy                      23
fl                        r
category            minivan
mean                   19.5
Name: 46, dtype: object
47 manufacturer          dodge
model           caravan 2wd
displ                   4.0
year                   2008
cyl                       6
trans              auto(l6)
drv                       f
cty                      16
hwy                      23
fl                        r
category            minivan
mean                   19.5
Name: 47, dtype: object
48 manufacturer                dodge
model           dakota pickup 4wd
displ                         3.7
year                         2008
cyl                             6
trans                  manual(m6)
drv                             4
cty                            15
hwy                            19
fl                              r
category                   pickup
mean                         17.0
Name: 48, dtype: object
49 manufacturer                dodge
model           dakota pickup 4wd
displ                         3.7
year                         2008
cyl                             6
trans                    auto(l4)
drv                             4
cty                            14
hwy                            18
fl                              r
category                   pickup
mean                         16.0
Name: 49, dtype: object
50 manufacturer                dodge
model           dakota pickup 4wd
displ                         3.9
year                         1999
cyl                             6
trans                    auto(l4)
drv                             4
cty                            13
hwy                            17
fl                              r
category                   pickup
mean                         15.0
Name: 50, dtype: object
51 manufacturer                dodge
model           dakota pickup 4wd
displ                         3.9
year                         1999
cyl                             6
trans                  manual(m5)
drv                             4
cty                            14
hwy                            17
fl                              r
category                   pickup
mean                         15.5
Name: 51, dtype: object
52 manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                            14
hwy                            19
fl                              r
category                   pickup
mean                         16.5
Name: 52, dtype: object
53 manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                            14
hwy                            19

### if statement
- 음료수 자판기 만들기

- 1번 누르면 콜라
- 2번 누르면 사이다
- 3번 누르면 환타
- 4번 누르면 취소
- 그외 번호 누르면 잘못된 번호입니다.

In [40]:
selected = int(input())

if selected == 1:
  print('콜라를 선택하셨습니다')
elif selected == 2:
  print('사이다를 선택하셨습니다')
elif selected == 3:
  print('환타를 선택하셨습니다')
elif selected == 4:
  print('취소를 선택하셨습니다')
else:
  print('잘못된 번호입니다.')

환타를 선택하셨습니다

In [21]:
## Assignment
## 
## 금액까지 추가해서
## 해당 콜라는 500, 사이다는 500, 환타는 300
## 내가 1,000원을 넣었을 때
## 전체 예산에서 구매 후에 남은 금액을 잔돈으로 표시해주고
## 예산을 넘어간 경우는 금액을 초과하였다고 alert 해주기
##
beverage_names = ['콜라', '사이다', '환타']
beverage_price = [500, 500, 300]


insert_coin = int(input('금액을 투입하십시오 : '))
print(f'투입된 금액은 {insert_coin}원 입니다.')
remain_coin = insert_coin


n_beverage = len(beverage_names)
selected = n_beverage

while selected:
  print('메뉴 선택 =>', end=' ')
  for i in range(n_beverage):
    print(f'{beverage_names[i]}({i+1}) : {beverage_price[i]}', end=' | ')
  print('반환(0)')  
  
  selected = int(input('메뉴를 선택해주십시오 : '))
  if selected == 0:
    break
  
  if remain_coin < beverage_price[selected-1]:
    print('잔액이 부족합니다.')
    continue
  else:
    remain_coin -= beverage_price[selected-1]
    print(f'선택된 음료는 {beverage_names[selected-1]} 입니다.')
    print(f'남은 잔액은 {remain_coin} 입니다.')

print(f'반환된 금액은 {remain_coin} 입니다.')

투입된 금액은 1000원 입니다.
메뉴 선택 => 콜라(1) : 500 | 사이다(2) : 500 | 환타(3) : 300 | 반환(0)
선택된 음료는 콜라 입니다.
남은 잔액은 500 입니다.
메뉴 선택 => 콜라(1) : 500 | 사이다(2) : 500 | 환타(3) : 300 | 반환(0)
선택된 음료는 환타 입니다.
남은 잔액은 200 입니다.
메뉴 선택 => 콜라(1) : 500 | 사이다(2) : 500 | 환타(3) : 300 | 반환(0)
잔액이 부족합니다.
메뉴 선택 => 콜라(1) : 500 | 사이다(2) : 500 | 환타(3) : 300 | 반환(0)
잔액이 부족합니다.
메뉴 선택 => 콜라(1) : 500 | 사이다(2) : 500 | 환타(3) : 300 | 반환(0)
반환된 금액은 200 입니다.

In [31]:

beverage_names = ['콜라', '사이다', '환타']
beverage_price = [500, 500, 300]


insert_coin = int(input('금액을 투입하십시오 : '))
print(f'투입된 금액은 {insert_coin}원 입니다.')
remain_coin = insert_coin


n_beverage = len(beverage_names)
selected = n_beverage

while selected:
  if not any(remain_coin >= price for price in beverage_price):
    break
  
  print('메뉴 선택 =>', end=' ')
  for i in range(n_beverage):
    if (remain_coin >= beverage_price[i]):
      print(f'{beverage_names[i]}({i+1}) : {beverage_price[i]}', end=' | ')
  print('반환(0)')  
  
  selected = int(input('메뉴를 선택해주십시오 : '))
  if selected == 0:
    break
  
  if remain_coin < beverage_price[selected-1]:
    print('잔액이 부족합니다.')
    continue
  else:
    remain_coin -= beverage_price[selected-1]
    print(f'선택된 음료는 {beverage_names[selected-1]} 입니다.')
    print(f'남은 잔액은 {remain_coin} 입니다.')

print(f'반환된 금액은 {remain_coin} 입니다.')

투입된 금액은 400원 입니다.
메뉴 선택 => 환타(3) : 300 | 반환(0)
잔액이 부족합니다.
메뉴 선택 => 환타(3) : 300 | 반환(0)
잔액이 부족합니다.
메뉴 선택 => 환타(3) : 300 | 반환(0)
잔액이 부족합니다.
메뉴 선택 => 환타(3) : 300 | 반환(0)
반환된 금액은 400 입니다.

#### 중첩루프
- 반복문 안에 반복문
- for i in range()
  - for j in range()

In [43]:
for i in range(8):
  for j in range(2):
    print(j, sep=' ', end=' ')
  print(i, sep =' ')

0 1 0
0 1 1
0 1 2
0 1 3
0 1 4
0 1 5
0 1 6
0 1 7

In [44]:
for i in range(2):
  for j in range(8):
    print(j, sep=' ', end=' ')
  print(i, sep =' ')

0 1 2 3 4 5 6 7 0
0 1 2 3 4 5 6 7 1

In [45]:
for i in range(2):
  for j in range(8):
    print('안쪽', j, sep=' ', end = '')
    print('바깥', i, end=' ')

안쪽 0바깥 0 안쪽 1바깥 0 안쪽 2바깥 0 안쪽 3바깥 0 안쪽 4바깥 0 안쪽 5바깥 0 안쪽 6바깥 0 안쪽 7바깥 0 안쪽 0바깥 1 안쪽 1바깥 1 안쪽 2바깥 1 안쪽 3바깥 1 안쪽 4바깥 1 안쪽 5바깥 1 안쪽 6바깥 1 안쪽 7바깥 1

In [46]:
for i in range(2):
  for j in range(3):
    for k in range(4):
      print(k, end=' ')
    print(j, end=' ')
  print(i, end=' ')

0 1 2 3 0 0 1 2 3 1 0 1 2 3 2 0 0 1 2 3 0 0 1 2 3 1 0 1 2 3 2 1

In [ ]:
*
 *
  *
   *
    *

# 대각선으로 별을 출력하기

In [49]:
for i in range(5):
  for j in range(5):
    print('*', end='')
  print()

*****
*****
*****
*****
*****

In [48]:
for i in range(5):
  for j in range(5):
    if i == j:
      print('*', end='')
    else:
      print(' ', end='')
  print()

*
 *
  *
   *
    *

In [50]:
for i in range(5):
  for j in range(5):
    if i == j:
      print(' ', end='')
    else:
      print('*', end='')
  print()

 ****
* ***
** **
*** *
****